<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>HookProbe</RootNamespace>
    <AssemblyName>HookProbe</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cubby.Shell\Cubby.Shell.csproj" />
  </ItemGroup>

</Project>